# Generated by Django 5.1.3 on 2024-11-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('movie', 'Movie'), ('series', 'Series'), ('anime', 'Anime')], max_length=15)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('register', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
