# Generated by Django 5.1.3 on 2024-11-16 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('movie', 'Movie'), ('series', 'Series'), ('anime', 'Anime')], max_length=10)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('register_date', models.DateField(auto_now_add=True)),
                ('register_time', models.TimeField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('update_time', models.TimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catálogo',
                'verbose_name_plural': 'Catálogo',
                'db_table': 'media_itens',
            },
        ),
    ]
