# Generated by Django 5.1.3 on 2024-11-14 18:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaitens',
            options={'verbose_name': 'Catálogo', 'verbose_name_plural': 'Catálogo'},
        ),
        migrations.RemoveField(
            model_name='mediaitens',
            name='register',
        ),
        migrations.RemoveField(
            model_name='mediaitens',
            name='update',
        ),
        migrations.AddField(
            model_name='mediaitens',
            name='register_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediaitens',
            name='register_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediaitens',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mediaitens',
            name='update_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
