# Generated by Django 5.1.3 on 2024-11-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaitens',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='mediaitens',
            name='update_time',
        ),
    ]
